### ISSUE TITLE
Kicker recipe will fail if any of directories contain space character.

### ISSUE THREAD

**Issue by psekara** [krzysztofzablocki/KZPlayground#12]
I had issue with kicker failing on directory that contains space character in its name.
```
execute("/usr/bin/python #{File.expand_path("~/.dyci/scripts/dyci-recompile.py")} #{"\"%s\"" % File.expand_path(file)}")
```
Replacing execute command in .kick file with the one above should fix it. The only difference is that I added quotation marks surrouding the file path using string format operator.

**Comment by krzysztofzablocki** [comment]
thanks, updated
