### ISSUE TITLE
KZP storyboard clashes with the "Main" storyboard of the actual app

### ISSUE THREAD

**Issue by leberwurstsaft** [krzysztofzablocki/KZPlayground#13]
Upon trying to integrate the playgrounds into our app to play with it, I realized that the app loaded right into the "Main" storyboard of KZPlayground, instead of the one the app itself uses, which incidentally goes by the same name "Main".

Looking at the code, KZPlayground is supposed to be loading the storyboard from the `[NSBundle bundleForClass:self]`, but somehow it doesn't seem to be in another bundle, since the wrong storyboard is used to initialize the app.

I have no clue about NSBundle and especially not in combination with CocoaPods, but a quick solution would be to avoid the "Main" name for KZPlayground's storyboard :smile:

**Comment by krzysztofzablocki** [comment]
good point, renamed

**Comment by leberwurstsaft** [comment]
Thank you 👍🏽
