### ISSUE TITLE
Injection attempting connection to: 127.0.0.1:31442

### ISSUE THREAD

**Issue by ianwhite2** [krzysztofzablocki/KZPlayground#19]
Hi,

I have removed the KZPlayground from the project but it still shows "Injection attempting connection to: 127.0.0.1:31442" in console ,How do i remove this log too ?

Thanks,
Ian

**Comment by trzeciak** [comment]
You can remove `Pods` directory, and `Podfile.lock`. next run `pod install`.

Damian.
