### ISSUE TITLE
Swift support

### ISSUE THREAD

**Issue by goktugyil** [krzysztofzablocki/KZPlayground#21]
> My playgrounds now support Swift code, to use that you should use injectionforxcode instead of Dyci, make sure to grab 0.4 Release for some simpler API.

Cocoapods doesn't have 0.4 pushed. Is the package supposed to be installing injection like the 0.3 version? Or is that meant to be a manual extra feature?

**Comment by krzysztofzablocki** [comment]
you should install https://github.com/johnno1962/injectionforxcode plugin for Swift support, I thought I pushed 0.4, I'll do that when I get back to Poland on the weekend
